

usedSharedRessources = {
    'marvinGui': [
        'processDict',
        'arduinoDict',
        'servoStaticDict',
        'cartDict',
        'environmentDict',

        'sharedDataUpdateQueue',
        'skeletonGuiUpdateQueue',
        'cartGuiUpdateQueue',
        'mapGuiUpdateQueue',
        'mainGuiUpdateQueue',
        'ikUpdateQueue',
        'skeletonRequestQueue',
        'cartRequestQueue',
        'speakRequestQueue',
        'playGestureQueue',
        'navManagerRequestQueue',
        'imageProcessingRequestQueue',
    ],

    'skeletonControl': [
        'processDict',
        #'arduinoDict',
        'servoStaticDict',
        #'cartDict'
        'sharedDataUpdateQueue',
        'skeletonGuiUpdateQueue',
        #'cartGuiUpdateQueue',
        'ikUpdateQueue',
        'skeletonRequestQueue',
        #'cartRequestQueue',
        'speakRequestQueue',
        #'SpeakRespondQueue',
        'imageProcessingRequestQueue',
    ],

    'cartControl': [
        'processDict',
        #'arduinoDict',
        'servoStaticDict',
        #'cartDict'
        'sharedDataUpdateQueue',
        #'skeletonGuiUpdateQueue',
        'cartGuiUpdateQueue',
        #'ikUpdateQueue',
        'skeletonRequestQueue',
        'cartRequestQueue',
        #'speakRequestQueue',
        # 'SpeakRespondQueue',
        'imageProcessingRequestQueue',
    ],

    'randomMoves': [
        'processDict',
        # 'arduinoDict',
        'servoStaticDict',
        # 'cartDict',

        'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        # 'ikUpdateQueue',
        'skeletonRequestQueue',
        # 'cartRequestQueue',
        'speakRequestQueue',
        # 'SpeakRespondQueue',
        # 'imageProcessingRequestQueue',
        ],

    'playGesture': [
        'processDict',
        # 'arduinoDict',
        'servoStaticDict',
        'cartDict',

        'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        # 'ikUpdateQueue',
        'skeletonRequestQueue',
        'cartRequestQueue',
        'speakRequestQueue',
        'playGestureQueue',
        # 'navManagerRequestQueue',
        # 'imageProcessingRequestQueue'
    ],
    'speechControl': [
        'processDict',
        # 'arduinoDict',
        'servoStaticDict',
        # 'cartDict',

        'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        # 'ikUpdateQueue',
        'skeletonRequestQueue',
        # 'cartRequestQueue',
        'speakRequestQueue',
        'playGestureQueue',
        # 'navManagerRequestQueue',
        # 'imageProcessingRequestQueue'
    ],
    'imageProcessing': [
        'processDict',
        # 'arduinoDict',
        # 'servoStaticDict',
        'cartDict',
        'environmentDict',

        'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        # 'ikUpdateQueue',
        'skeletonRequestQueue',
        'cartRequestQueue',
        #'speakRequestQueue',
        # 'SpeakRespondQueue',
        'imageProcessingRequestQueue'
    ],
    'navManager': [
        'processDict',
        # 'arduinoDict',
        'servoStaticDict',
        'cartDict',
        'environmentDict',

        'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        # 'ikUpdateQueue',
        'skeletonRequestQueue',
        'cartRequestQueue',
        # 'speakRequestQueue',
        # 'SpeakRespondQueue',
        'navManagerRequestQueue',
        'imageProcessingRequestQueue'
    ],
    'stickFigure': [
        'processDict',
        # 'arduinoDict',
        'servoStaticDict',
        # 'cartDict',

        #'sharedDataUpdateQueue',
        # 'skeletonGuiUpdateQueue',
        # 'cartGuiUpdateQueue',
        'ikUpdateQueue',
        #'skeletonRequestQueue',
        # 'cartRequestQueue',
        #'speakRequestQueue',
        #'playGestureQueue',
        #'navManagerRequestQueue',
        # 'imageProcessingRequestQueue'
    ],
}
